-- DBWarp Blueprint 1.6 Oracle Basic preview - DBA capture
-- Server family: oracle-21c
-- Run through capture.sh or capture.ps1 as the dedicated collector account.
-- Do not run as SYS, SYSTEM, or a broadly privileged DBA account.
-- The protected raw spool is sanitized locally into the transferable spool.
-- Both contain real catalogue names and must stay inside your organisation.
-- Generated from DBWarp Blueprint's Oracle Basic catalogue queries. Do not edit.
-- POSIX cksum: 0223434411
SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 32767
SET LONGCHUNKSIZE 32767
SET WRAP OFF
SET TRIMOUT ON
SET TRIMSPOOL ON
SET TERMOUT OFF
SET TIMING OFF
SET AUTOPRINT OFF
SET AUTOTRACE OFF
SET PAUSE OFF
SET SQLCASE MIXED
SET ROWLIMIT OFF
SET CMDSEP OFF
SET SQLTERMINATOR ";"
SET MARKUP HTML OFF
SET MARKUP CSV OFF
SET DEFINE OFF
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_CALENDAR = 'GREGORIAN';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF9';
ALTER SESSION SET NLS_COMP = 'BINARY';
ALTER SESSION SET NLS_SORT = 'BINARY';
DECLARE
C_EXPECTED_MAJOR CONSTANT PLS_INTEGER := 21;
C_EXPECTED_MINOR CONSTANT PLS_INTEGER := -1;
C_HEX_DIGITS CONSTANT VARCHAR2(16) := '0123456789ABCDEF';
V_INPUT CLOB := :DBWARP_BP_OWNER_HEX_LIST;
V_START PLS_INTEGER := 1;
V_STOP PLS_INTEGER;
V_HEX VARCHAR2(256);
V_PREVIOUS_HEX VARCHAR2(256);
V_OWNER VARCHAR2(128);
V_OWNER_COUNT PLS_INTEGER := 0;
V_OWNER_PRESENT PLS_INTEGER;
V_SERVER_VERSION VARCHAR2(64);
FUNCTION HEX_COMPARE(P_LEFT VARCHAR2, P_RIGHT VARCHAR2) RETURN PLS_INTEGER IS
V_LIMIT PLS_INTEGER := LEAST(LENGTH(P_LEFT), LENGTH(P_RIGHT));
V_LEFT PLS_INTEGER;
V_RIGHT PLS_INTEGER;
BEGIN
FOR I IN 1 .. V_LIMIT LOOP
V_LEFT := INSTR(C_HEX_DIGITS, SUBSTR(P_LEFT, I, 1));
V_RIGHT := INSTR(C_HEX_DIGITS, SUBSTR(P_RIGHT, I, 1));
IF V_LEFT < V_RIGHT THEN RETURN -1; END IF;
IF V_LEFT > V_RIGHT THEN RETURN 1; END IF;
END LOOP;
IF LENGTH(P_LEFT) < LENGTH(P_RIGHT) THEN RETURN -1; END IF;
IF LENGTH(P_LEFT) > LENGTH(P_RIGHT) THEN RETURN 1; END IF;
RETURN 0;
END;
BEGIN
IF SYS_CONTEXT('USERENV', 'CON_NAME') = 'CDB$ROOT' THEN
RAISE_APPLICATION_ERROR(-20005, 'connect-to-pdb');
END IF;
SELECT VERSION INTO V_SERVER_VERSION FROM SYS.V_$INSTANCE;
IF TO_NUMBER(REGEXP_SUBSTR(V_SERVER_VERSION, '^[0-9]+')) <> C_EXPECTED_MAJOR OR
(C_EXPECTED_MINOR >= 0 AND
TO_NUMBER(REGEXP_SUBSTR(V_SERVER_VERSION, '[0-9]+', 1, 2)) <> C_EXPECTED_MINOR) THEN
RAISE_APPLICATION_ERROR(-20004, 'wrong-script-family');
END IF;
IF V_INPUT IS NULL OR NOT REGEXP_LIKE(V_INPUT, '^[0-9A-F]+(,[0-9A-F]+)*$') THEN
RAISE_APPLICATION_ERROR(-20001, 'owner-input');
END IF;
LOOP
V_STOP := INSTR(V_INPUT, ',', V_START);
IF V_STOP = 0 THEN V_STOP := LENGTH(V_INPUT) + 1; END IF;
V_HEX := SUBSTR(V_INPUT, V_START, V_STOP - V_START);
IF MOD(LENGTH(V_HEX), 2) <> 0 OR LENGTH(V_HEX) > 256 OR
(V_PREVIOUS_HEX IS NOT NULL AND HEX_COMPARE(V_PREVIOUS_HEX, V_HEX) >= 0) THEN
RAISE_APPLICATION_ERROR(-20001, 'owner-input');
END IF;
V_OWNER := UTL_I18N.RAW_TO_CHAR(HEXTORAW(V_HEX), 'AL32UTF8');
IF V_OWNER IS NULL OR LENGTHB(V_OWNER) > 128 OR REGEXP_LIKE(V_OWNER, '[[:cntrl:]]') THEN
RAISE_APPLICATION_ERROR(-20001, 'owner-input');
END IF;
V_OWNER_COUNT := V_OWNER_COUNT + 1;
IF V_OWNER_COUNT > 16384 THEN
RAISE_APPLICATION_ERROR(-20001, 'owner-input');
END IF;
V_PREVIOUS_HEX := V_HEX;
EXIT WHEN V_STOP > LENGTH(V_INPUT);
V_START := V_STOP + 1;
END LOOP;
BEGIN
EXECUTE IMMEDIATE
'SELECT COUNT(*) FROM SYS.ALL_USERS '
|| 'WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(USERNAME, ''AL32UTF8'')) IN ('
|| 'SELECT CAST(REGEXP_SUBSTR(:OWNER_LIST, ''[^,]+'', 1, LEVEL) '
|| 'AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= '
|| 'REGEXP_COUNT(:OWNER_LIST, '','') + 1)'
INTO V_OWNER_PRESENT USING V_INPUT, V_INPUT;
IF V_OWNER_PRESENT <> V_OWNER_COUNT THEN
RAISE_APPLICATION_ERROR(-20006, 'owner-not-found');
END IF;
EXCEPTION
WHEN OTHERS THEN
-- ALL_USERS is normally public but may be revoked
-- on hardened estates. In that case the converter proves each
-- owner from the granted floor catalogues instead.
IF SQLCODE NOT IN (-942, -1031) THEN RAISE; END IF;
END;
END;
/
WHENEVER SQLERROR CONTINUE NONE
SPOOL dbwarp-blueprint-oracle-basic.raw
COLUMN DBWARP_BP_FRAME FORMAT A32000
PROMPT DBWARP_BP_RAW|H|2|oracle-21c|cc50460b7fca1e4b9011a8c2a04003acff2320b0a6ff2793c8a45b708ca906d4|958df23fa184bb807a46ae57b28448ca80870d594eb226777db010931851d47e|29
SELECT 'DBWARP_BP_RAW|C|' || TO_CHAR(ROUND(
(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - DATE '1970-01-01') * 86400000),
'FM99999999999999999990', 'NLS_NUMERIC_CHARACTERS=''.,''') FROM DUAL;
SELECT 'DBWARP_BP_RAW|M|CAPTURED_AT|T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(
TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'),
'AL32UTF8')) FROM DUAL;
SELECT 'DBWARP_BP_RAW|M|PRINCIPAL|T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(
SYS_CONTEXT('USERENV', 'SESSION_USER'), 'AL32UTF8')) FROM DUAL;
SELECT 'DBWARP_BP_RAW|M|DATABASE|T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(
SYS_CONTEXT('USERENV', 'DB_NAME') || '/' || SYS_CONTEXT('USERENV', 'CON_NAME'),
'AL32UTF8')) FROM DUAL;
SELECT 'DBWARP_BP_RAW|M|SERVER_VERSION|T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(
VERSION, 'AL32UTF8')) FROM SYS.V_$INSTANCE;
SELECT 'DBWARP_BP_RAW|M|CLIENT_RELEASE|T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(
:DBWARP_BP_CLIENT_RELEASE, 'AL32UTF8')) FROM DUAL;
SELECT 'DBWARP_BP_RAW|O|' || TO_CHAR(LEVEL, 'FM99999999999999999990') || '|T' ||
CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL)
AS VARCHAR2(256))
FROM DUAL
CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1;
PROMPT DBWARP_BP_RAW|Q|1|oracle-users|ALL_USERS|2|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|1|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|1|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.username IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.username), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.username), 'AL32UTF8')) END || '|' ||
CASE WHEN q.oracle_maintained IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.oracle_maintained), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.oracle_maintained), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT username, oracle_maintained FROM SYS.ALL_USERS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(username, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|1|E
PROMPT DBWARP_BP_RAW|Q|2|oracle-objects|DBA_OBJECTS|8|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|2|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|2|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.object_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.object_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.status IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) END || '|' ||
CASE WHEN q.temporary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.generated IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) END || '|' ||
CASE WHEN q.secondary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.editionable IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.editionable), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.editionable), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, object_name, object_type, status, temporary, generated, secondary, editionable FROM SYS.DBA_OBJECTS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|2|E
PROMPT DBWARP_BP_RAW|Q|3|oracle-tables|DBA_TABLES|18|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|3|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|3|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.tablespace_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|' ||
CASE WHEN q.avg_row_len IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) END || '|' ||
CASE WHEN q.last_analyzed IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partitioned IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) END || '|' ||
CASE WHEN q.temporary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.iot_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.nested IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nested), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nested), 'AL32UTF8')) END || '|' ||
CASE WHEN q.compression IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) END || '|' ||
CASE WHEN q.iot_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.secondary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.external IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.external), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.external), 'AL32UTF8')) END || '|' ||
CASE WHEN q.cluster_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cluster_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cluster_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.dropped IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.dropped), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.dropped), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_created IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, tablespace_name, num_rows, blocks, avg_row_len, last_analyzed, partitioned, temporary, iot_type, nested, compression, iot_name, secondary, external, cluster_name, dropped, segment_created FROM SYS.DBA_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|3|E
PROMPT DBWARP_BP_RAW|Q|4|oracle-object-tables|DBA_OBJECT_TABLES|18|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|4|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|4|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.tablespace_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|' ||
CASE WHEN q.avg_row_len IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) END || '|' ||
CASE WHEN q.last_analyzed IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partitioned IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) END || '|' ||
CASE WHEN q.temporary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.temporary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.iot_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.nested IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nested), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nested), 'AL32UTF8')) END || '|' ||
CASE WHEN q.compression IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) END || '|' ||
CASE WHEN q.iot_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.iot_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.secondary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.external IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.external), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.external), 'AL32UTF8')) END || '|' ||
CASE WHEN q.cluster_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cluster_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cluster_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.dropped IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.dropped), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.dropped), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_created IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, tablespace_name, num_rows, blocks, avg_row_len, last_analyzed, partitioned, temporary, iot_type, nested, compression, iot_name, secondary, external, cluster_name, dropped, segment_created FROM SYS.DBA_OBJECT_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|4|E
PROMPT DBWARP_BP_RAW|Q|5|oracle-external-tables|DBA_EXTERNAL_TABLES|2|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|5|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|5|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name FROM SYS.DBA_EXTERNAL_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|5|E
PROMPT DBWARP_BP_RAW|Q|6|oracle-nested-tables|DBA_NESTED_TABLES|4|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|6|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|6|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.parent_table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parent_table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parent_table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.parent_table_column IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parent_table_column), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parent_table_column), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, parent_table_name, parent_table_column FROM SYS.DBA_NESTED_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|6|E
PROMPT DBWARP_BP_RAW|Q|7|oracle-mview-logs|DBA_MVIEW_LOGS|4|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|7|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|7|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.log_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.log_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.log_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.log_table IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.log_table), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.log_table), 'AL32UTF8')) END || '|' ||
CASE WHEN q.master IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.master), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.master), 'AL32UTF8')) END || '|' ||
CASE WHEN q.primary_key IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.primary_key), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.primary_key), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT log_owner, log_table, master, primary_key FROM SYS.DBA_MVIEW_LOGS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(log_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|7|E
PROMPT DBWARP_BP_RAW|Q|8|oracle-queue-tables|DBA_QUEUE_TABLES|2|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|8|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|8|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.queue_table IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.queue_table), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.queue_table), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, queue_table FROM SYS.DBA_QUEUE_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|8|E
PROMPT DBWARP_BP_RAW|Q|9|oracle-tab-columns|DBA_TAB_COLUMNS|13|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|9|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|9|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_id IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_id), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_id), 'AL32UTF8')) END || '|' ||
CASE WHEN q.data_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.data_length IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_length), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_length), 'AL32UTF8')) END || '|' ||
CASE WHEN q.data_precision IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_precision), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_precision), 'AL32UTF8')) END || '|' ||
CASE WHEN q.data_scale IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_scale), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.data_scale), 'AL32UTF8')) END || '|' ||
CASE WHEN q.nullable IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nullable), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.nullable), 'AL32UTF8')) END || '|' ||
CASE WHEN q.char_length IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.char_length), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.char_length), 'AL32UTF8')) END || '|' ||
CASE WHEN q.char_used IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.char_used), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.char_used), 'AL32UTF8')) END || '|' ||
CASE WHEN q.default_length IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.default_length), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.default_length), 'AL32UTF8')) END || '|' ||
CASE WHEN q.default_on_null IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.default_on_null), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.default_on_null), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, column_name, column_id, data_type, data_length, data_precision, data_scale, nullable, char_length, char_used, default_length, default_on_null FROM SYS.DBA_TAB_COLUMNS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|9|E
PROMPT DBWARP_BP_RAW|Q|10|oracle-tab-cols-hidden|DBA_TAB_COLS|7|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|10|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|10|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.hidden_column IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.hidden_column), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.hidden_column), 'AL32UTF8')) END || '|' ||
CASE WHEN q.virtual_column IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.virtual_column), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.virtual_column), 'AL32UTF8')) END || '|' ||
CASE WHEN q.internal_column_id IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.internal_column_id), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.internal_column_id), 'AL32UTF8')) END || '|' ||
CASE WHEN q.user_generated IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.user_generated), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.user_generated), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, column_name, hidden_column, virtual_column, internal_column_id, user_generated FROM SYS.DBA_TAB_COLS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|10|E
PROMPT DBWARP_BP_RAW|Q|11|oracle-identity-columns|DBA_TAB_IDENTITY_COLS|5|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|11|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|11|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.generation_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generation_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generation_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.sequence_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.sequence_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.sequence_name), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, column_name, generation_type, sequence_name FROM SYS.DBA_TAB_IDENTITY_COLS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|11|E
PROMPT DBWARP_BP_RAW|Q|12|oracle-indexes|DBA_INDEXES|18|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|12|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|12|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.uniqueness IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.uniqueness), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.uniqueness), 'AL32UTF8')) END || '|' ||
CASE WHEN q.distinct_keys IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.distinct_keys), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.distinct_keys), 'AL32UTF8')) END || '|' ||
CASE WHEN q.clustering_factor IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.clustering_factor), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.clustering_factor), 'AL32UTF8')) END || '|' ||
CASE WHEN q.leaf_blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.leaf_blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.leaf_blocks), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.last_analyzed IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partitioned IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioned), 'AL32UTF8')) END || '|' ||
CASE WHEN q.status IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) END || '|' ||
CASE WHEN q.generated IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) END || '|' ||
CASE WHEN q.secondary IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.secondary), 'AL32UTF8')) END || '|' ||
CASE WHEN q.visibility IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.visibility), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.visibility), 'AL32UTF8')) END || '|' ||
CASE WHEN q.join_index IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.join_index), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.join_index), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_created IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_created), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, index_name, table_owner, table_name, index_type, uniqueness, distinct_keys, clustering_factor, leaf_blocks, num_rows, last_analyzed, partitioned, status, generated, secondary, visibility, join_index, segment_created FROM SYS.DBA_INDEXES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(table_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|12|E
PROMPT DBWARP_BP_RAW|Q|13|oracle-index-columns|DBA_IND_COLUMNS|7|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|13|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|13|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.index_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) END || '|' ||
CASE WHEN q.descend IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.descend), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.descend), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT index_owner, index_name, table_name, column_name, column_position, descend, table_owner FROM SYS.DBA_IND_COLUMNS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(table_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|13|E
PROMPT DBWARP_BP_RAW|Q|14|oracle-index-expressions|DBA_IND_EXPRESSIONS|4|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|14|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|14|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.index_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT index_owner, index_name, column_position, table_owner FROM SYS.DBA_IND_EXPRESSIONS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(table_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|14|E
PROMPT DBWARP_BP_RAW|Q|15|oracle-constraints|DBA_CONSTRAINTS|15|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|15|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|15|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.constraint_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.constraint_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.r_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.r_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.r_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.r_constraint_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.r_constraint_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.r_constraint_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.delete_rule IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.delete_rule), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.delete_rule), 'AL32UTF8')) END || '|' ||
CASE WHEN q.status IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) END || '|' ||
CASE WHEN q.deferrable IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deferrable), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deferrable), 'AL32UTF8')) END || '|' ||
CASE WHEN q.validated IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.validated), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.validated), 'AL32UTF8')) END || '|' ||
CASE WHEN q.deferred IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deferred), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deferred), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.generated IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.generated), 'AL32UTF8')) END || '|' ||
CASE WHEN q.is_not_null_constraint IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.is_not_null_constraint), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.is_not_null_constraint), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, constraint_name, constraint_type, table_name, r_owner, r_constraint_name, delete_rule, status, deferrable, validated, deferred, index_owner, index_name, generated, CASE WHEN constraint_type = 'C' AND REGEXP_LIKE(search_condition_vc, '^"([^"]|"")+" IS NOT NULL$') THEN 'Y' ELSE 'N' END AS is_not_null_constraint FROM SYS.DBA_CONSTRAINTS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|15|E
PROMPT DBWARP_BP_RAW|Q|16|oracle-constraint-columns|DBA_CONS_COLUMNS|5|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|16|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|16|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.constraint_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.constraint_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.position), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, constraint_name, table_name, column_name, position FROM SYS.DBA_CONS_COLUMNS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|16|E
PROMPT DBWARP_BP_RAW|Q|17|oracle-part-tables|DBA_PART_TABLES|6|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|17|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|17|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partitioning_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioning_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partitioning_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.subpartitioning_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartitioning_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartitioning_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partition_count IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_count), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_count), 'AL32UTF8')) END || '|' ||
CASE WHEN q.interval IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.interval), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.interval), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, partitioning_type, subpartitioning_type, partition_count, interval FROM SYS.DBA_PART_TABLES WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|17|E
PROMPT DBWARP_BP_RAW|Q|18|oracle-tab-partitions|DBA_TAB_PARTITIONS|6|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|18|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|18|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.table_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partition_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partition_position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_position), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT table_owner, table_name, partition_name, partition_position, num_rows, blocks FROM SYS.DBA_TAB_PARTITIONS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(table_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|18|E
PROMPT DBWARP_BP_RAW|Q|19|oracle-tab-subpartitions|DBA_TAB_SUBPARTITIONS|7|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|19|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|19|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.table_owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partition_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.subpartition_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartition_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartition_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.subpartition_position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartition_position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.subpartition_position), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT table_owner, table_name, partition_name, subpartition_name, subpartition_position, num_rows, blocks FROM SYS.DBA_TAB_SUBPARTITIONS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(table_owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|19|E
PROMPT DBWARP_BP_RAW|Q|20|oracle-part-key-columns|DBA_PART_KEY_COLUMNS|5|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|20|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|20|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.object_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_position IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_position), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, name, object_type, column_name, column_position FROM SYS.DBA_PART_KEY_COLUMNS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|20|E
PROMPT DBWARP_BP_RAW|Q|21|oracle-segments|DBA_SEGMENTS|6|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|21|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|21|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.tablespace_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.tablespace_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.bytes IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.bytes), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.bytes), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, segment_name, segment_type, tablespace_name, bytes, blocks FROM SYS.DBA_SEGMENTS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|21|E
PROMPT DBWARP_BP_RAW|Q|22|oracle-lobs|DBA_LOBS|11|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|22|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|22|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.column_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.column_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.segment_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.segment_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.index_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.index_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.chunk IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.chunk), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.chunk), 'AL32UTF8')) END || '|' ||
CASE WHEN q.in_row IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.in_row), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.in_row), 'AL32UTF8')) END || '|' ||
CASE WHEN q.securefile IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.securefile), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.securefile), 'AL32UTF8')) END || '|' ||
CASE WHEN q.compression IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.compression), 'AL32UTF8')) END || '|' ||
CASE WHEN q.deduplication IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deduplication), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.deduplication), 'AL32UTF8')) END || '|' ||
CASE WHEN q.encrypt IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.encrypt), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.encrypt), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, column_name, segment_name, index_name, chunk, in_row, securefile, compression, deduplication, encrypt FROM SYS.DBA_LOBS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|22|E
PROMPT DBWARP_BP_RAW|Q|23|oracle-tab-statistics|DBA_TAB_STATISTICS|14|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|23|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|N|N|N|N|N|N|N|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|23|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.owner IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.owner), 'AL32UTF8')) END || '|' ||
CASE WHEN q.table_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.table_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.partition_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.partition_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.num_rows IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.num_rows), 'AL32UTF8')) END || '|' ||
CASE WHEN q.blocks IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.blocks), 'AL32UTF8')) END || '|' ||
CASE WHEN q.avg_row_len IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.avg_row_len), 'AL32UTF8')) END || '|' ||
CASE WHEN q.last_analyzed IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.last_analyzed), 'AL32UTF8')) END || '|' ||
CASE WHEN q.stale_stats IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.stale_stats), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.stale_stats), 'AL32UTF8')) END || '|' ||
CASE WHEN q.object_type IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.object_type), 'AL32UTF8')) END || '|' ||
CASE WHEN q.sample_size IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.sample_size), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.sample_size), 'AL32UTF8')) END || '|' ||
CASE WHEN q.global_stats IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.global_stats), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.global_stats), 'AL32UTF8')) END || '|' ||
CASE WHEN q.user_stats IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.user_stats), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.user_stats), 'AL32UTF8')) END || '|' ||
CASE WHEN q.stattype_locked IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.stattype_locked), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.stattype_locked), 'AL32UTF8')) END || '|' ||
CASE WHEN q.scope IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.scope), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.scope), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT owner, table_name, partition_name, num_rows, blocks, avg_row_len, last_analyzed, stale_stats, object_type, sample_size, global_stats, user_stats, stattype_locked, scope FROM SYS.DBA_TAB_STATISTICS WHERE RAWTOHEX(UTL_I18N.STRING_TO_RAW(owner, 'AL32UTF8')) IN (SELECT CAST(REGEXP_SUBSTR(:DBWARP_BP_OWNER_HEX_LIST, '[^,]+', 1, LEVEL) AS VARCHAR2(256)) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(:DBWARP_BP_OWNER_HEX_LIST, ',') + 1)) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|23|E
PROMPT DBWARP_BP_RAW|Q|24|oracle-nls|NLS_DATABASE_PARAMETERS|2|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|24|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|24|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.parameter IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parameter), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parameter), 'AL32UTF8')) END || '|' ||
CASE WHEN q.value IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.value), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.value), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT parameter, value FROM SYS.NLS_DATABASE_PARAMETERS) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|24|E
PROMPT DBWARP_BP_RAW|Q|25|oracle-version|PRODUCT_COMPONENT_VERSION|3|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|25|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|25|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.product IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.product), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.product), 'AL32UTF8')) END || '|' ||
CASE WHEN q.version IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version), 'AL32UTF8')) END || '|' ||
CASE WHEN q.version_full IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version_full), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version_full), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT product, version, version_full FROM SYS.PRODUCT_COMPONENT_VERSION) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|25|E
PROMPT DBWARP_BP_RAW|Q|26|oracle-database|V_$DATABASE|4|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|26|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|26|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.platform_name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.platform_name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.platform_name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.database_role IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.database_role), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.database_role), 'AL32UTF8')) END || '|' ||
CASE WHEN q.open_mode IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.open_mode), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.open_mode), 'AL32UTF8')) END || '|' ||
CASE WHEN q.cdb IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cdb), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.cdb), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT platform_name, database_role, open_mode, cdb FROM SYS.V_$DATABASE) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|26|E
PROMPT DBWARP_BP_RAW|Q|27|oracle-instance|V_$INSTANCE|3|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|27|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|27|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.version IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.version), 'AL32UTF8')) END || '|' ||
CASE WHEN q.status IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.status), 'AL32UTF8')) END || '|' ||
CASE WHEN q.parallel IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parallel), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.parallel), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT version, status, parallel FROM SYS.V_$INSTANCE) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|27|E
PROMPT DBWARP_BP_RAW|Q|28|oracle-containers|V_$CONTAINERS|3|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|28|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|28|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.con_id IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.con_id), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.con_id), 'AL32UTF8')) END || '|' ||
CASE WHEN q.open_mode IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.open_mode), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.open_mode), 'AL32UTF8')) END || '|' ||
CASE WHEN q.restricted IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.restricted), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.restricted), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT con_id, open_mode, restricted FROM SYS.V_$CONTAINERS) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|28|E
PROMPT DBWARP_BP_RAW|Q|29|oracle-capacity-parameters|V_$PARAMETER|3|B
SELECT CASE
WHEN LENGTH(DBWARP_BP_FULL_FRAME) > 32000 THEN
TO_CLOB('DBWARP_BP_RAW|R|29|') ||
TO_CHAR(DBWARP_BP_ROW_NUMBER, 'FM99999999999999999990') ||
'|L|N|N|Z'
ELSE DBWARP_BP_FULL_FRAME
END AS DBWARP_BP_FRAME
FROM (SELECT ROWNUM AS DBWARP_BP_ROW_NUMBER,
TO_CLOB('DBWARP_BP_RAW|R|29|') ||
TO_CHAR(ROWNUM, 'FM99999999999999999990') || '|' ||
CASE WHEN q.name IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.name), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.name), 'AL32UTF8')) END || '|' ||
CASE WHEN q.value IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.value), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.value), 'AL32UTF8')) END || '|' ||
CASE WHEN q.isdefault IS NULL THEN 'N' WHEN UTL_RAW.LENGTH(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.isdefault), 'AL32UTF8')) > 1000 THEN 'L' ELSE 'T' || RAWTOHEX(UTL_I18N.STRING_TO_RAW(TO_CHAR(q.isdefault), 'AL32UTF8')) END || '|Z' AS DBWARP_BP_FULL_FRAME
FROM (SELECT name, value, isdefault FROM SYS.V_$PARAMETER WHERE LOWER(name) IN ('cpu_count','memory_target','sga_target','sga_max_size')) q) DBWARP_BP_BOUNDED_ROWS;
PROMPT DBWARP_BP_RAW|Q|29|E
SELECT 'DBWARP_BP_RAW|X|29|' || TO_CHAR(ROUND(
(CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - DATE '1970-01-01') * 86400000),
'FM99999999999999999990', 'NLS_NUMERIC_CHARACTERS=''.,''') FROM DUAL;
SPOOL OFF
EXIT SUCCESS
