#!/usr/bin/env python3
"""Fail closed when a DBWarp Blueprint public source tree is unsafe."""

from __future__ import annotations

import argparse
import json
import os
import re
import stat
import subprocess
import sys
from pathlib import Path


REQUIRED = {
    "AGENTS.md",
    "CLAUDE.md",
    "BUILD.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "Cargo.lock",
    "Cargo.toml",
    "GEMINI.md",
    "GROK.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "MACHINE_TRANSLATIONS.md",
    "README.md",
    "SECURITY.md",
    "SUPPORT.md",
    "THIRD_PARTY_NOTICES.md",
    "assets/fonts/dm-sans/OFL.txt",
    "build.sh",
    "crates/dbwarp-blueprint-core/SOURCE_MANIFEST.sha256",
    "rust-toolchain.toml",
    "rustup-init.sha256",
    "src/main.rs",
    "third-party-licenses/MANIFEST.json",
    "tools/check_public_tree.py",
    "tools/check_linux_lazy_gssapi.py",
    "tools/generate_third_party_notices.py",
    "vendor/mysql_async/LICENSE-APACHE",
    "vendor/mysql_async/LICENSE-MIT",
    "vendor/mysql_async/MODIFICATIONS.md",
    "vendor/libgssapi-sys/LICENSE-MIT",
    "vendor/libgssapi-sys/MODIFICATIONS.md",
    "vendor/tiberius/LICENSE-APACHE.txt",
    "vendor/tiberius/LICENSE-MIT.txt",
    "vendor/tiberius/MODIFICATIONS.md",
    "vendor/winauth/LICENSE-APACHE",
    "vendor/winauth/LICENSE-MIT",
    "vendor/winauth/MODIFICATIONS.md",
}

# These entry points must also retain their executable modes in a Git index.
# Windows filesystems cannot reliably represent POSIX executable permissions.
REQUIRED_EXECUTABLES = {
    "blueprint_format.py",
    "build.sh",
    "verify.sh",
    "tools/check_blueprint_core_sync.sh",
    "tools/check_public_tree.py",
    "tools/check_linux_lazy_gssapi.py",
    "tools/check_release_archive.py",
    "tools/check_rust_advisories.sh",
    "tools/generate_provenance.py",
    "tools/generate_sbom.py",
    "tools/generate_third_party_notices.py",
    "tools/test_check_public_tree.py",
    "tools/test_check_linux_lazy_gssapi.py",
}
REQUIRED.update(REQUIRED_EXECUTABLES)

FORBIDDEN_PATH_PARTS = {"artifact-publish", "ci", "internal", "tmp"}
FORBIDDEN_PATH_PREFIXES = ("tests/manual",)
# Generated bytecode and build output are not source-release inputs.
IGNORED_PATH_PARTS = {".git", ".hg", ".svn", "target", "__pycache__"}

# Keep this standalone checker free of organization-private identifiers.
# Structural checks reject non-public repository and lab-host classes without
# embedding a list of private repository names in the public checker itself.
DBWARP_REPOSITORY_URL = re.compile(r"github\.com/DBWarp/([A-Za-z0-9._-]+)", re.I)
DBWARP_REPOSITORY_LAYOUT = re.compile(
    r"\b(dbwarp-[a-z0-9._-]+)/(?:build|docs|internal|scripts|src)(?:/|\b)", re.I
)
# Crates this repository actually publishes. A path like
# `dbwarp-blueprint-core/src/` is this tree's own shared core, not a reference
# to a private sibling repository, so it must not trip the layout rule. Listing
# the public crates keeps the rule's coverage of genuinely private names such
# as `dbwarp-<something>/src` intact; loosening the pattern would not.
PUBLIC_DBWARP_PROJECTS = frozenset({"dbwarp-blueprint", "dbwarp-blueprint-core"})
PRIVATE_TLD = re.compile(
    r"\b[a-z0-9-]+\.[a-z0-9-]+\.test\b", re.I
)
NON_BLUEPRINT_DBWARP_COMMAND = re.compile(
    r"`[ \t]*dbwarp[ \t]+([a-z][a-z0-9-]*)[ \t]*`", re.I
)
MARKDOWN_LINK = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")


def files_under(root: Path) -> list[Path]:
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file()
        and not set(path.relative_to(root).parts).intersection(IGNORED_PATH_PARTS)
    )


def markdown_link_target(raw: str) -> str:
    value = raw.strip()
    if value.startswith("<") and ">" in value:
        return value[1 : value.index(">")]
    return value.split(maxsplit=1)[0] if value else ""


def inspect_text(path: str, text: str, failures: list[str]) -> None:
    for match in DBWARP_REPOSITORY_URL.finditer(text):
        repository = match.group(1)
        normalized = repository[:-4] if repository.casefold().endswith(".git") else repository
        if normalized.casefold() != "dbwarp-blueprint":
            failures.append(f"non-public DBWarp repository URL: {path}")
    for match in DBWARP_REPOSITORY_LAYOUT.finditer(text):
        if match.group(1).casefold() not in PUBLIC_DBWARP_PROJECTS:
            failures.append(f"non-public DBWarp repository layout: {path}")
    if PRIVATE_TLD.search(text):
        failures.append(f"private-network hostname: {path}")
    for match in NON_BLUEPRINT_DBWARP_COMMAND.finditer(text):
        if match.group(1).casefold() != "blueprint":
            failures.append(f"non-public DBWarp command: {path}")


def validate_executable_modes(root: Path, required: set[str]) -> list[str]:
    """Check disk modes and, when present, the candidate's own Git index.

    Do not inspect a parent repository: an unstaged export inside its scratch
    directory is not that repository's index. Checking the index as well as
    disk catches lost modes even when core.filemode is false.
    """
    failures: list[str] = []
    for relative in sorted(required):
        path = root / relative
        if path.is_symlink() or not path.is_file():
            failures.append(f"missing or unsafe public executable: {relative}")
        elif os.name != "nt" and not path.stat().st_mode & stat.S_IXUSR:
            failures.append(f"public executable lost its executable bit: {relative}")
    if (root / ".git").exists():
        try:
            git_env = dict(os.environ)
            for key in ("GIT_INDEX_FILE", "GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR"):
                git_env.pop(key, None)
            result = subprocess.run(
                ["git", "--git-dir", str(root / ".git"), "--work-tree", str(root),
                 "ls-files", "--stage", "-z"], cwd=root, env=git_env,
                check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            )
            modes = {}
            for entry in result.stdout.split(b"\0"):
                if entry:
                    metadata, name = entry.split(b"\t", 1)
                    mode, _, stage = metadata.decode("ascii").split()
                    if stage != "0":
                        raise ValueError("unmerged public index")
                    modes[name.decode("utf-8")] = mode
            for relative in sorted(required):
                if modes.get(relative) != "100755":
                    failures.append(
                        f"public Git index must track {relative} as 100755; "
                        f"stage it with git update-index --chmod=+x -- {relative}"
                    )
        except (OSError, ValueError, subprocess.CalledProcessError) as exc:
            failures.append(f"could not verify public Git executable modes: {exc}")
    elif os.name == "nt":
        failures.append(
            "cannot verify public executable bits on Windows without a staged "
            "candidate Git index; stage the candidate with explicit 100755 modes "
            "and rerun this checker, or export on a POSIX filesystem"
        )
    return failures


def validate_public_tree(root: Path, allow_vendored_dependencies: bool = False) -> list[str]:
    root = root.resolve()
    failures: list[str] = []
    failures.extend(validate_executable_modes(root, REQUIRED_EXECUTABLES))
    relative_files = {path.relative_to(root).as_posix() for path in files_under(root)}

    for required in sorted(REQUIRED - relative_files):
        failures.append(f"missing required public file: {required}")
    for path in sorted(relative_files):
        if path.startswith("vendor-crates/"):
            if not allow_vendored_dependencies:
                failures.append(f"unexpected generated dependency path: {path}")
            # Cargo.lock and the archive validator bind this generated graph.
            # First-party prose checks are not applied to third-party sources.
            continue
        parts = set(Path(path).parts)
        if parts & FORBIDDEN_PATH_PARTS or any(
            path == prefix or path.startswith(prefix + "/")
            for prefix in FORBIDDEN_PATH_PREFIXES
        ):
            failures.append(f"forbidden public path: {path}")
            continue
        file_path = root / path
        try:
            data = file_path.read_bytes()
        except OSError as exc:
            failures.append(f"could not read public file: {path}: {exc}")
            continue
        text = data.decode("utf-8", errors="replace")
        inspect_text(path, text, failures)
        if file_path.suffix.lower() == ".md":
            try:
                text = data.decode("utf-8")
            except UnicodeDecodeError:
                failures.append(f"public Markdown is not UTF-8: {path}")
                continue
            for match in MARKDOWN_LINK.finditer(text):
                target = markdown_link_target(match.group(1))
                if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                    continue
                relative_target = target.split("#", 1)[0].split("?", 1)[0]
                resolved_target = (file_path.parent / relative_target).resolve()
                if root != resolved_target and root not in resolved_target.parents:
                    failures.append(f"public Markdown link escapes the source tree: {path}: {target}")
                elif not resolved_target.exists():
                    failures.append(f"public Markdown link target is missing: {path}: {target}")

    checksum_path = root / "rustup-init.sha256"
    if checksum_path.is_file():
        try:
            checksum_text = checksum_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            failures.append(f"could not validate rustup-init.sha256: {exc}")
        else:
            for line in checksum_text.splitlines():
                if re.match(r"^0{64}\s", line):
                    failures.append("rustup-init.sha256 contains a placeholder hash")

    apache_path = root / "LICENSE-APACHE"
    if apache_path.is_file():
        try:
            apache = apache_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            failures.append(f"could not validate LICENSE-APACHE: {exc}")
        else:
            if len(apache.encode("utf-8")) < 10_000 or "3. Grant of Patent License." not in apache:
                failures.append("LICENSE-APACHE is not the complete Apache License 2.0 text")

    manifest_path = root / "third-party-licenses" / "MANIFEST.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            failures.append(f"invalid third-party licence manifest: {exc}")
        else:
            if manifest.get("schema") != "dbwarp-blueprint-third-party-licenses/v1":
                failures.append("third-party licence manifest has an invalid schema")
            packages = manifest.get("packages")
            if not isinstance(packages, list) or manifest.get("third_party_package_count") != len(packages):
                failures.append("third-party licence manifest package count does not reconcile")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--allow-vendored-dependencies",
        action="store_true",
        help="allow the generated Cargo vendor-crates tree without treating third-party text as first-party",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    failures = validate_public_tree(root, args.allow_vendored_dependencies)
    if failures:
        for failure in failures:
            print(f"public-tree error: {failure}", file=sys.stderr)
        return 1
    print(f"public source tree valid: {len(files_under(root))} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
