#!/usr/bin/env python3
"""Generate and verify the locked third-party licence inventory.

The binary archives carry this generated directory verbatim. Collection is
based on Cargo's all-feature resolved graph so target-specific dependencies are
covered even when this command runs on Linux.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "third-party-licenses"
NOTICES = ROOT / "THIRD_PARTY_NOTICES.md"
OVERRIDES = ROOT / "tools" / "third-party-license-overrides"
MARKER = ".generated-by-dbwarp-blueprint"
FIRST_PARTY = {"dbwarp-blueprint", "dbwarp-blueprint-core"}
LICENCE_NAME = re.compile(
    r"^(?:licen[cs]e|copying|notice|copyright)(?:$|[-._])", re.IGNORECASE
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def resolved_packages() -> tuple[list[dict[str, object]], int]:
    environment = os.environ.copy()
    environment.setdefault("CARGO_TARGET_DIR", str(ROOT / "tmp" / "notice-target"))
    result = subprocess.run(
        [
            "cargo",
            "metadata",
            "--locked",
            "--all-features",
            "--format-version",
            "1",
        ],
        cwd=ROOT,
        env=environment,
        check=True,
        stdout=subprocess.PIPE,
    )
    metadata = json.loads(result.stdout)
    resolved = {node["id"] for node in metadata["resolve"]["nodes"]}
    packages = [package for package in metadata["packages"] if package["id"] in resolved]
    third_party = [package for package in packages if package["name"] not in FIRST_PARTY]
    third_party.sort(key=lambda package: (package["name"], package["version"], package["id"]))
    return third_party, len(packages)


def safe_component(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9._+-]+", value):
        raise SystemExit(f"unsafe package path component: {value!r}")
    return value


def licence_files(package_root: Path) -> list[Path]:
    found: list[Path] = []
    for path in package_root.rglob("*"):
        if not path.is_file() or not LICENCE_NAME.match(path.name):
            continue
        relative = path.relative_to(package_root)
        if any(part in {".git", "target"} for part in relative.parts):
            continue
        found.append(path)
    return sorted(found, key=lambda path: path.relative_to(package_root).as_posix())


def fallback_licence_files(package: dict[str, object]) -> list[tuple[str, bytes]]:
    name = safe_component(str(package["name"]))
    version = safe_component(str(package["version"]))
    override = OVERRIDES / f"{name}-{version}"
    if override.is_dir():
        return [
            (path.relative_to(override).as_posix(), path.read_bytes())
            for path in sorted(override.rglob("*"))
            if path.is_file()
        ]
    expression = str(package.get("license") or "")
    if "Apache-2.0" in expression:
        return [("SELECTED-LICENSE-APACHE-2.0.txt", (ROOT / "LICENSE-APACHE").read_bytes())]
    return []


def metadata_notice(package: dict[str, object]) -> bytes:
    authors = package.get("authors") or []
    lines = [
        "The published Cargo package did not contain a standalone licence file.",
        "Its package metadata declares the following licensing information:",
        "",
        f"name: {package['name']}",
        f"version: {package['version']}",
        f"license: {package.get('license') or 'license-file declared in package metadata'}",
        f"authors: {', '.join(str(author) for author in authors) or 'not declared'}",
        f"repository: {package.get('repository') or 'not declared'}",
        "",
        "The matching package source is included in the vendored source archive.",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def build_tree(destination: Path, packages: list[dict[str, object]], total: int) -> str:
    destination.mkdir(parents=True)
    (destination / MARKER).write_text(
        "Generated by tools/generate_third_party_notices.py; do not edit.\n",
        encoding="utf-8",
    )
    records: list[dict[str, object]] = []
    for package in packages:
        name = safe_component(str(package["name"]))
        version = safe_component(str(package["version"]))
        package_root = Path(str(package["manifest_path"])).resolve().parent
        package_dir = destination / "crates" / f"{name}-{version}"
        copied: list[dict[str, str]] = []
        for source in licence_files(package_root):
            relative = source.relative_to(package_root)
            target = package_dir / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            data = source.read_bytes()
            target.write_bytes(data)
            copied.append({"path": relative.as_posix(), "sha256": sha256(data)})
        if not copied:
            fallbacks = fallback_licence_files(package)
            if not fallbacks:
                fallbacks = [("PACKAGE-METADATA.txt", metadata_notice(package))]
            for relative_name, data in fallbacks:
                target = package_dir / relative_name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
                copied.append({"path": relative_name, "sha256": sha256(data)})
        records.append(
            {
                "name": name,
                "version": version,
                "license": package.get("license") or "NOASSERTION",
                "license_file": bool(package.get("license_file")),
                "repository": package.get("repository"),
                "files": copied,
            }
        )

    manifest = {
        "schema": "dbwarp-blueprint-third-party-licenses/v1",
        "cargo_resolved_package_count": total,
        "first_party_package_count": total - len(packages),
        "third_party_package_count": len(packages),
        "packages": records,
    }
    (destination / "MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return render_notices(records, total)


def render_notices(records: list[dict[str, object]], total: int) -> str:
    lines = [
        "# Third-party notices",
        "",
        "This release's all-feature Cargo graph contains "
        f"{total} packages: 2 first-party DBWarp crates and {len(records)} "
        "third-party crates. Every third-party name, version, declared licence, "
        "and copied notice file is recorded in `third-party-licenses/MANIFEST.json`. "
        "The complete copied texts are distributed in `third-party-licenses/crates/`.",
        "",
        "## Required and modified components",
        "",
        "### ring",
        "",
        "The `ring` distribution contains ISC code, BoringSSL-derived code, "
        "once_cell-derived code, and Fiat Cryptography code. Its top-level licence "
        "and every licence file it references are reproduced under "
        "`third-party-licenses/crates/ring-0.17.14/`.",
        "",
        "### mysql_async",
        "",
        "DBWarp Blueprint uses a modified `mysql_async` 0.34.2. The Apache-2.0 and "
        "MIT texts and the required modification notice are in "
        "`vendor/mysql_async/`; the same licence texts are also present in the "
        "generated third-party bundle.",
        "",
        "### mimalloc",
        "",
        "The binary links the mimalloc allocator through the `mimalloc` and "
        "`libmimalloc-sys` Rust crates. Their package and embedded native-source "
        "licence files are included in the generated third-party bundle.",
        "",
        "## DM Sans",
        "",
        "Generated PowerPoint decks embed DM Sans static font faces. Copyright "
        "2014 The DM Sans Project Authors. DM Sans is distributed under the SIL "
        "Open Font License, Version 1.1; see `assets/fonts/dm-sans/OFL.txt`. No "
        "Reserved Font Name is declared for these bundled files.",
        "",
        "## Locked Cargo inventory",
        "",
        "| Crate | Version | Declared licence |",
        "|---|---:|---|",
    ]
    for record in records:
        expression = str(record["license"]).replace("|", "\\|")
        lines.append(f"| `{record['name']}` | `{record['version']}` | `{expression}` |")
    lines.append("")
    return "\n".join(lines)


def file_map(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): sha256(path.read_bytes())
        for path in root.rglob("*")
        if path.is_file()
    }


def validate_required_licences(root: Path) -> list[str]:
    failures: list[str] = []
    apache = (ROOT / "LICENSE-APACHE").read_text(encoding="utf-8")
    if len(apache.encode("utf-8")) < 10_000 or "3. Grant of Patent License." not in apache:
        failures.append("LICENSE-APACHE is not the complete Apache License 2.0 text")
    mysql_notice = ROOT / "vendor" / "mysql_async" / "MODIFICATIONS.md"
    if not mysql_notice.is_file():
        failures.append("vendor/mysql_async/MODIFICATIONS.md is missing")
    ring = root / "crates" / "ring-0.17.14"
    required_ring = {
        "LICENSE",
        "LICENSE-BoringSSL",
        "LICENSE-other-bits",
        "src/polyfill/once_cell/LICENSE-APACHE",
        "src/polyfill/once_cell/LICENSE-MIT",
        "third_party/fiat/LICENSE",
    }
    present = {path.relative_to(ring).as_posix() for path in ring.rglob("*") if path.is_file()}
    for missing in sorted(required_ring - present):
        failures.append(f"ring notice is missing: {missing}")
    return failures


def write_outputs() -> None:
    packages, total = resolved_packages()
    if OUTPUT.exists():
        marker = OUTPUT / MARKER
        if not marker.is_file():
            raise SystemExit(f"refusing to replace unowned directory: {OUTPUT}")
        shutil.rmtree(OUTPUT)
    notices = build_tree(OUTPUT, packages, total)
    NOTICES.write_text(notices, encoding="utf-8")
    failures = validate_required_licences(OUTPUT)
    if failures:
        raise SystemExit("\n".join(failures))
    print(f"generated notices for {len(packages)} third-party crates")


def check_outputs() -> None:
    packages, total = resolved_packages()
    scratch = ROOT / "tmp"
    scratch.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="third-party-check-", dir=scratch) as raw:
        candidate = Path(raw) / "third-party-licenses"
        notices = build_tree(candidate, packages, total)
        failures = validate_required_licences(candidate)
        if not OUTPUT.is_dir():
            failures.append("third-party-licenses directory is missing")
        elif file_map(candidate) != file_map(OUTPUT):
            failures.append("third-party-licenses does not match the locked Cargo graph")
        if not NOTICES.is_file() or NOTICES.read_text(encoding="utf-8") != notices:
            failures.append("THIRD_PARTY_NOTICES.md does not match the locked Cargo graph")
        if failures:
            for failure in failures:
                print(f"third-party notice error: {failure}", file=sys.stderr)
            raise SystemExit(1)
    print(f"third-party notices valid: {len(packages)} crates")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="replace generated outputs")
    args = parser.parse_args()
    if args.write:
        write_outputs()
    else:
        check_outputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
