-- DBWarp Blueprint 1.6 preview - Oracle Basic DBA capture dispatcher
-- Invoked by capture.sh or capture.ps1 after they safely encode owner names.
SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET WRAP OFF
SET TRIMOUT ON
SET TRIMSPOOL ON
SET TERMOUT OFF
SET TIMING OFF
SET AUTOPRINT OFF
SET AUTOTRACE OFF
SET PAUSE OFF
SET SQLCASE MIXED
SET ROWLIMIT OFF
SET CMDSEP OFF
SET SQLTERMINATOR ";"
SET MARKUP HTML OFF
SET MARKUP CSV OFF
SET DEFINE ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE
VARIABLE DBWARP_BP_OWNER_HEX_LIST CLOB
VARIABLE DBWARP_BP_CLIENT_RELEASE VARCHAR2(64)
@./dbwarp-blueprint-owner-bind.sql
BEGIN
  :DBWARP_BP_CLIENT_RELEASE := '&_SQLPLUS_RELEASE';
END;
/
SET DEFINE OFF
VARIABLE DBWARP_BP_CAPTURE_SCRIPT VARCHAR2(128)
BEGIN
  SELECT CASE
           WHEN TO_NUMBER(REGEXP_SUBSTR(VERSION, '^[0-9]+')) = 12 AND
                TO_NUMBER(REGEXP_SUBSTR(VERSION, '[0-9]+', 1, 2)) = 1
             THEN 'oracle-12c/basic-12.1.sql'
           WHEN TO_NUMBER(REGEXP_SUBSTR(VERSION, '^[0-9]+')) = 12 AND
                TO_NUMBER(REGEXP_SUBSTR(VERSION, '[0-9]+', 1, 2)) = 2
             THEN 'oracle-12c/basic-12.2.sql'
           WHEN TO_NUMBER(REGEXP_SUBSTR(VERSION, '^[0-9]+')) = 19
             THEN 'oracle-19c/basic.sql'
           WHEN TO_NUMBER(REGEXP_SUBSTR(VERSION, '^[0-9]+')) = 21
             THEN 'oracle-21c/basic.sql'
           WHEN TO_NUMBER(REGEXP_SUBSTR(VERSION, '^[0-9]+')) = 23
             THEN 'oracle-26ai/basic.sql'
         END
    INTO :DBWARP_BP_CAPTURE_SCRIPT
    FROM SYS.V_$INSTANCE;
  IF :DBWARP_BP_CAPTURE_SCRIPT IS NULL THEN
    RAISE_APPLICATION_ERROR(-20004, 'unsupported-server-family');
  END IF;
END;
/
SET DEFINE ON
COLUMN DBWARP_BP_CAPTURE_SCRIPT NEW_VALUE DBWARP_BP_CAPTURE_SCRIPT NOPRINT
SELECT :DBWARP_BP_CAPTURE_SCRIPT AS DBWARP_BP_CAPTURE_SCRIPT FROM DUAL;
@@&DBWARP_BP_CAPTURE_SCRIPT
EXIT FAILURE
